### ISSUE TITLE
Extending One of the Clients

### ISSUE THREAD

**Issue by isaac2004** [titarenko/OAuth2#106]
What is the best approach to extend one of the clients? I am only going to be using YahooClient and have a handful of Api calls I want to add. Should just inherit from YahooClient?

**Comment by niemyjski** [comment]
I'd either inherit or copy the source and change it up how you want. What did you end up doing?

**Comment by isaac2004** [comment]
@niemyjski stripped out the Yahoo provider  and extended it to my needs. Worked well
