### ISSUE TITLE
Saving the token somewhere

### ISSUE THREAD

**Issue by isaac2004** [titarenko/OAuth2#107]
It looks like if you refresh the auth page after getting the token gives you an exception because the AccessToken/RefreshToken isn't being saved on subsequent calls. Should the token be stored somewhere so these calls don't need to request the token again?

**Comment by niemyjski** [comment]
Did you end up finding a solution for this? I'm not sure if this is something that we should be saving. Our api calls are pretty stateless

**Comment by isaac2004** [comment]
@niemyjski you can add some state using MVC, that is what I did.

**Comment by ProNotion** [comment]
@isaac2004 Would you mind sharing some detail on your solution please?

**Comment by isaac2004** [comment]
@ProNotion I ended up storing the token in a service and handled passing and refreshing using DI. I will add some code to this if I remember.
