### ISSUE TITLE
Any additional resources/documentation available?

### ISSUE THREAD

**Issue by LVG5Pelican** [titarenko/OAuth2#110]
I'm fairly new to Oauth2 - are there any further resources available that I can look at? Maybe a sample implementation somewhere?

Can I use this to implement authorization grant in the asp.net framework?

**Comment by sarjarapu** [comment]
I second the request. 

The readme file says - "simplicity in usage - so even newbie can just call ... , well-documented ". I would love to use your lib, but could barely move forward with either GoogleClient and / or CustomClient. Having simple either of these examples in docs would help lot more people to use this lib.

I tried to digest the mock Tests for further understand, but not sure where you got the from OAuthClientDescendant either.

**Comment by niemyjski** [comment]
We'd really love some user contributed docs from end users. You could take a look at my application in how were use it (https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Api/Controllers/AuthController.cs).

**Comment by SamuelDebruyn** [comment]
+1, both the readme and the NuGet say "well-documented" while this project has no documentation whatsoever

**Comment by niemyjski** [comment]
This is an open source project provided to you all at $0. Please give back to the community and others by helping with the documentation. All pr's or wiki edits are greatly welcomed.
