### ISSUE TITLE
Could you please Strong sign the DLL in Nuget

### ISSUE THREAD

**Issue by mikkeljohnsen** [titarenko/OAuth2#111]
Could you please Strong sign the DLL in Nuget

**Comment by niemyjski** [comment]
Can you please submit a pull request for this.

**Comment by Sbaia** [comment]
Normally strong signing is done in NuGet deploy procedure, to avoid to commit pfx and password in repository.

**Comment by mikkeljohnsen** [comment]
Not an issue for us anymore. Have stopped adding to GAC

**Comment by niemyjski** [comment]
We could add it and I'm fine with including the key right in the repository because it's absolute joke and the general consensus is that it's ok (I'm pretty against strong naming). If you need it again let e know and I can add it to the next minor release.
