### ISSUE TITLE
RestSharp version issue

### ISSUE THREAD

**Issue by MrSong0607** [titarenko/OAuth2#113]
when i update RestSharp to latest stable 106.1.0 in nuget,i got this error:
`The type 'IRestResponse' is defined in an assembly that is not referenced. You must add a reference to assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null'`
how can i upgrade RestSharp version

**Comment by niemyjski** [comment]
You'll need to add a binding redirect or use the latest nightly build on nuget. Please let us know if you have any questions.

**Comment by MrSong0607** [comment]
I added the node to app.config,but i get the same error too
  ```
 <dependentAssembly>
        <assemblyIdentity name="RestSharp" publicKeyToken="null" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-106.1.0.0" newVersion="106.1.0.0" />
      </dependentAssembly>
```

**Comment by niemyjski** [comment]
You are probably missing the strong name public key token. Also if you are running on .net core I don't think you can do assembly redirects like this anymore.

**Comment by MrSong0607** [comment]
i'm using .net framework 4.6.1,and i change the config to 
```
    <dependentAssembly>
        <assemblyIdentity name="RestSharp" publicKeyToken="598062e77f915f75" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-106.1.0.0" newVersion="106.1.0.0" />
      </dependentAssembly>
```
i get the above error too

**Comment by niemyjski** [comment]
I'm not sure, I'd recommend bringing up the issue with RestSharp via GitHu
or use the latest nightly build here which targets the 106.1 assembly

Thanks
-Blake Niemyjski
