### ISSUE TITLE
using in local app

### ISSUE THREAD

**Issue by jaayb** [titarenko/OAuth2#115]
how would you handle using this in a local winforms app as far as redirect uri?
Thanks

**Comment by niemyjski** [comment]
We currently don't have a sample of this and I've never had to do this but I'd recommend seeing what others are doing: https://stackoverflow.com/questions/22870231/is-oauth-possible-for-c-sharp-windows-application and https://blogs.msdn.microsoft.com/rgregg/2014/10/02/easy-msa-oauth-in-windows-forms/ If you find the solution please update this issue / feel free to submit a sample in a pr.
