### ISSUE TITLE
VkClient is outdated

### ISSUE THREAD

**Issue by lucky-ly** [titarenko/OAuth2#116]
VkClient doesn't work since Feb 1 2018 because since then **v** (api version) parameter is required for api calls.
And the api call used for retrieving user data is outdated too - **uids** parameter is unknown now, **user_ids** should be used instead.

**Comment by niemyjski** [comment]
Can you please submit a pr for this.

Thanks
-Blake Niemyjski

**Comment by niemyjski** [comment]
Thanks for the PR!
