### ISSUE TITLE
Library use old CommonServiceLocator version

### ISSUE THREAD

**Issue by tomasr78** [titarenko/OAuth2#127]
The OAuth2 library use CommonServiceLocator 1.3 version of service locator and binds to Microsoft.Practices.ServiceLocation assembly. 

The CommonServiceLocator 2.0 do not have such assembly anymore, are you planning to update?

**Comment by niemyjski** [comment]
I'm not sure where you are seeing this. I don't see a single dependency on any DI framework or uses service locator pattern.

**Comment by tomasr78** [comment]
The OAuth2 throw exception on initialization at 

`  var authorizationRoot = new AuthorizationRoot();`
