### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by titarenko** [titarenko/OAuth2#19]
Write at least basic documentation on internals of OAuth2 library implementation.

**Comment by black-snow** [comment]
Where do I find the documentation?

**Comment by titarenko** [comment]
Do you want to enhance or use this library? If latter, then please read `README.md`.

**Comment by black-snow** [comment]
Hi,

I was planning to use this lib to authorize with a bunch of different services such as Google Drive and Dropbox from my .net WPF application. Sadly I don't know how to use/extends your project (seems to be tailored to MVC web apps, right?).

**Comment by titarenko** [comment]
Yes, initially it was made for web applications.

**Comment by black-snow** [comment]
Do you know of any other project that could fit my needs? I'm about to write my own OAuth2 code flow using RestSharp since I couldn't find any read2go solution that satisfied me.

Thanks in advance.

**Comment by titarenko** [comment]
Sorry, I haven't worked on desktop applications where OAuth2 authentication was required, so I can't give any useful advice here.

**Comment by titarenko** [comment]
BTW, if you will find good solution for this, please post link here, I would be glad to add it as notice to docs.

**Comment by black-snow** [comment]
I will but amazingly it looks pretty bad.

**Comment by niemyjski** [comment]
If someone would like to create a pr for this, we would greatly appreciate it. Closing this to clean up issues we all want or know needs to get done.
