### ISSUE TITLE
Use-case - service layer wants access token, front-end is responsible for providing it

### ISSUE THREAD

**Issue by agibalov** [titarenko/OAuth2#35]
First of all, guys you build the great thing. I really like OAuth2 and its idea of being as simple and easy to use as possible. Thank you for this.

I'd like to propose some changes which I believe won't make the entire solution more complicated, but will enable few other use-cases.

As a distributed web-solution developer, I want my service layer to be designed as a standalone web API. This API will provide authentication methods like:

```
POST /AuthenticateWithGoogle/?accessToken={accessToken}
POST /AuthenticateWithFacebook/?accessToken={accessToken}
etc.
```

These methods will provide a `session token` which the service users will then use to tell the service who they are when they want to access the API:

```
GET /Dashboard/?sessionToken={sessionToken}
```

In this scenario, front-end (be it a web application or mobile client) is responsible for getting the google access token and then providing it to web API for authentication. Service behind web API will use this token to understand if or not we already have this user registered, create/update this user's details, etc.

I would really love OAuth2 library to provide a simple API to independently "authenticate and get access token" and "use access token to get user details". Based on the code I've seen, everything is already there, but it's just not a part of user API. Here's a pseudo code snippet:

```
// Web application
public ActionResult RedirectToGoogleAuthentication()
{
  return Redirect(_googleClient.GetAuthenticationUri());
}

public ActionResult GoogleAuthenticationCallback(string code)
{
  var accessToken = _googleClient.GetAccessToken(code);
  var serviceAuthResult = _myService.AuthenticateWithGoogle(accessToken);
  // DONE!
}

// Web API
public AuthenticationResult AuthenticateWithGoogle(string accessToken)
{
  // _googleClient is either OAuth2's GoogleClient or something hand-made
  var userDetails = _googleClient.GetUserInfo(accessToken);
  var user = _authenticationService.GetOrCreateUserByGoogleUserId(userDetails.Id);
  return StartSessionForUser(user);
}
```

**Comment by niemyjski** [comment]
I think that we could make this easier to use but I also think it's up to the client side tech that you are using to provide a token. In this case mvc for the redirect where as this library can work anywhere.
