### ISSUE TITLE
Exeption in Twitter client then call GetLoginLinkUri

### ISSUE THREAD

**Issue by samz-me** [titarenko/OAuth2#38]
Exception of type 'OAuth2.Client.UnexpectedResponseException' was thrown.
version OAuth2 0.8.29 from nuget

**Comment by pankajray** [comment]
Please help:- 

When login via fb I got exception at this point:
return new RedirectResult(GetClient().GetLoginLinkUri());..................Exception

Exception is:- 

An exception of type 'System.MissingMethodException' occurred in eCommerce.dll but was not handled in user code

Additional information: Method not found: 'RestSharp.IRestRequest RestSharp.IRestRequest.AddObject(System.Object)'.


Thanks In advance
