### ISSUE TITLE
Instagram client authorize exception

### ISSUE THREAD

**Issue by AndreiPiatrou** [titarenko/OAuth2#41]
As said in http://instagram.com/developer/authentication/ we have to use POST request instead GET. As I see in your RequestFactoryExtensions.CreateRequest creates only GET requests. Can you adjust to use POST requests to Instagram access_token requests?
Sorry, the problem is in getUserInfo endpoint. It is incorrect. And this request needs to be invoked with url parameter "acces_token". Can you fix this problem? I realy need in it. Thanks.

**Comment by niemyjski** [comment]
Can you please submit a pull request for this.

**Comment by niemyjski** [comment]
@AndreyPetrov1991 Are you still seeing this issue? Can you submit a pr for this?
