### ISSUE TITLE
Facebook and Windows Live profile photo

### ISSUE THREAD

**Issue by kpocza** [titarenko/OAuth2#42]
In case of Windows Live client the profile photo is not valid. The avatar photo Url points to a target where there is no photo.  

I see some complex Url combination logic in WindowsLiveClient.cs. Will it work for users who integrated their Windows 8, 8.1 with their live account?

You should use something like that: https://apis.live.net/v5.0/{0}/picture 
where {0} is the userId.

Related documentation: http://msdn.microsoft.com/en-us/library/live/hh243648.aspx

Facebook avatar Urls that are provided by Oauth2 point to very small images even the Large ones.

The following call will give the correct profile photo Url:
https://graph.facebook.com/{0}/picture?type={1}
where {0} is the user id and {1] is the type (small, normal, large).

According to this there is a better method:
https://developers.facebook.com/docs/graph-api/reference/user/picture/

**Comment by niemyjski** [comment]
Could you please provide a pull request for this.

**Comment by niemyjski** [comment]
@kpocza could you please create a pr for this.

**Comment by kpocza** [comment]
Sorry, I've missed the requests for pr, as I see multiple times. Shame on me.
After reading my own comment I myself can understand it only partially. The API interfaces may have been changed in the last almost 3 years since then I raised the above issue.
However looking back to the project I was working on that time, I've found some evidences for some workarounds for exactly the same problem stated by me in the past.

Please refer to the attachment:
[Providers.zip](https://github.com/titarenko/OAuth2/files/613898/Providers.zip)

If you need any further explanations regarding to the code I attached, feel free to contact me. For sure I'll reply in some years. Just kidding. :) I visit GitHub more regularly nowadays.
