### ISSUE TITLE
Получение информации о пользователе только по Access token

### ISSUE THREAD

**Issue by Cepega** [titarenko/OAuth2#45]
Хотелось бы иметь возможность получаться информацию о пользователе только при помощи Access token. Например, если я использую библиотеку при создании API для мобильного приложения. В самом приложении происходит авторизация, где получаем access token.
Сейчас получить данные можно только через QueryString.

-----
I would like to be able to obtain information about the user only through Access token. For example, if I use the API library when creating mobile applications. In the application there is authorization, which obtain access token.
Now you get the data only through the QueryString.

**Comment by niemyjski** [comment]
Could you please translate this to english :).

**Comment by niemyjski** [comment]
@titarenko was this ever implemented?
