### ISSUE TITLE
C# 5.0 Async API

### ISSUE THREAD

**Issue by neurospeech** [titarenko/OAuth2#53]
This is new feature request to implement async await pattern for Client token authorization.

**Comment by niemyjski** [comment]
+1

**Comment by niemyjski** [comment]
Could you please do a pull request for this!

**Comment by niemyjski** [comment]
I'm closing this as we know we want this.. if someone could please create a pr for this, it would be greatly appreciated.

**Comment by SamuelDebruyn** [comment]
Working on a PR for this. I have some questions regarding breaking changes and backwards compatibility. Right now I'm providing async alternatives for the existing methods, but because some of them are `virtual`, this means some code is duplicated. Should I remove the non-async methods?

**Comment by niemyjski** [comment]
Yes, I vote to remove the non async methods.
