### ISSUE TITLE
Remove System.Web Dependency 

### ISSUE THREAD

**Issue by jzielke** [titarenko/OAuth2#54]
First, thanks for the great implementation of OAuth2.  First package I found that was easy to reuse for different providers.

Is there a way to remove the System.Web Dependency in UriUtility.cs.  Just wondering if anyone has done it already?

I would like to use this with Nancy if possible.  Works great in our MVC website, but need it for a Nancy installation.

**Comment by niemyjski** [comment]
Would you please do a pull request for this. I'd love to see this as it would make it easier to port this library to dnx

**Comment by niemyjski** [comment]
@jzielke We need to remove this when we port to .net core. Would you mind looking into this and submit a pr for this. In the mean time, I'm closing this issue.
