### ISSUE TITLE
Issue with updating to the latest version of RestSharp

### ISSUE THREAD

**Issue by niemyjski** [titarenko/OAuth2#58]
There is an issue when updating to 105 of restsharp ( https://github.com/restsharp/RestSharp/issues/595 ). I think the only thing that needs to be done is the code needs to pull the new restsharp package and recompile.

**Comment by niemyjski** [comment]
an we update this? This is breaking me right now..

**Comment by samppis** [comment]
I'm experiencing this issue as well and it would be great to have support for the lastest RestSharp. I'm now having a lot of compatibility issues with other libraries that require a later version of it.

**Comment by niemyjski** [comment]
Yea same here

**Comment by titarenko** [comment]
Hi guys,

I'm very sorry for such long delay in maintenance of this library (I haven't touched it during about 1 year). I'm not Windows user at the moment, so I have some obstacles with testing before releasing code. But I will try to get Windows PC for a week to merge pull requests and resolve issues.

**Comment by samppis** [comment]
Thanks! That would be much appreaciated :)

**Comment by jphellemons** [comment]
Would be nice to have this fix in a new release of the nuget package! :+1:

**Comment by niemyjski** [comment]
+1

**Comment by iqbalsinghkhanna** [comment]
Hi,
I am having this issue

Method not found: 'Void RestSharp.RestClient.set_BaseUrl(System.String)'.

Please let me know how i can fix it.

**Comment by niemyjski** [comment]
You need to downgrade to RestSharp 104.

**Comment by niemyjski** [comment]
@titarenko, can I please get read/write access to github and nuget.

**Comment by titarenko** [comment]
Hi @niemyjski 

Thanks for willingness to put efforts on maintenance! I will give you access.

P. S. Unfortunately, no luck with Windows for me, I'm still without environment to write C# code for .NET, and latest pull request merge ended up with broken tests on CI, so I was not able to release it to NuGet.

**Comment by titarenko** [comment]
Added you as a collaborator, so you now have push rights. Tell me your NuGet username and I will add you as owner.

**Comment by niemyjski** [comment]
No problem, I'll help where I can. It's niemyjski and my email can be found on my github profile (Is there anything I need to do for the CI)? Those errors seem really goofy. Have you tried using xamerian studio or the recently released visual studio code for osx on osx? It's what I use on my mac and it works great.

**Comment by niemyjski** [comment]
@titarenko  for some reason I couldn't be invited to nuget, can you please try again,

**Comment by niemyjski** [comment]
This will be fixed once we get the unit tests fixed in #70.
