### ISSUE TITLE
Store extra oauth user data as extended data on the userinfo object

### ISSUE THREAD

**Issue by niemyjski** [titarenko/OAuth2#60]
It seems like we are getting a lot of valuable information returned by our user info responses and we throw it away like a list of all their email addresses, sex/age and much more... It would be nice if this was shredded and anything that we didn't know about was placed in key value pairs on a userinfo data property.

I'd be more than happy to pair on this functionally..

**Comment by ejsmith** [comment]
+1

**Comment by ArtsevDmitry** [comment]
For example, need phone, but this property not presented in UserInfo :)

**Comment by jordisan** [comment]
We are using your fantastic library , but now we need to get additional user info from LinkedIn; concretely, the country of the user (inside location): https://developer.linkedin.com/docs/fields/basic-profile

Note that location is a structured data item, so maybe key-value pairs is not the best solution.

What do you recommend us? Extending your library somehow? Thanks

**Comment by niemyjski** [comment]
Previously in a different library, we always parsed the data into key value pairs. Currently this functionality isn't available (myself or someone needs to build it) but we should have a dictionary where we can return all the extended data items.

**Comment by niemyjski** [comment]
In this case you could parse it out into location.name = value or you could store it as json?

**Comment by jordisan** [comment]
Maybe we could add a `AllData` member to `UserInfo` class... (maybe XDocument or JObject); and then store there all the user data coming from the server

**Comment by ejsmith** [comment]
I would think you would want to store the values in a dictionary and not use something that is transport specific like jobject and xdoc.

**Comment by jordisan** [comment]
Sure, @ejsmith ... I was just thinking about a quick-and-dirty solution :)

**Comment by weihangChen** [comment]
I am doing the same thing, I think the quickest solution is to change the 

```
 private readonly IRequestFactory _requestFactory;
 private readonly OAuth2ConfigurationSection _configurationSection;
```

to protected in AuthorizationRoot, then we can subclass AuthorizationRoot, overriding the 

```
public virtual IEnumerable<IClient> Clients
        {
            get
            {
                var types = this.GetClientTypes().ToList();
                Func<ClientConfiguration, Type> getType = 
                    configuration => types.FirstOrDefault(x => x.Name == configuration.ClientTypeName);

                return
                    _configurationSection.Services.AsEnumerable()
                                        .Where(configuration => configuration.IsEnabled)
                                        .Select(configuration => new { configuration, type = getType(configuration) })
                                        .Where(o => o.type != null)
                                        .Select(o => (IClient)Activator.CreateInstance(o.type, _requestFactory, o.configuration));                
            }
        }
```

we can add our custom types to the web.config
<add clientType="GoogleClient" clientCustomType ="OAuth2.Example.Models.MyGoogleClient"........>

then use reflection to create our own clientimpl instance

**Comment by weihangChen** [comment]
I got this working in a quick way, without modifying existing API

```
using System.Collections.Generic;
using System.Linq;
using OAuth2.Configuration;
using OAuth2.Infrastructure;
using OAuth2.Models;
using OAuth2.Client;

namespace OAuth2.Example.Models
{
    public class MyGoogleClient : OAuth2.Client.Impl.GoogleClient
    {

        public MyGoogleClient(IRequestFactory factory, IClientConfiguration configuration)
            : base(factory, configuration)
        {
        }


        protected override UserInfo ParseUserInfo(string content)
        {
            return base.ParseUserInfo(content);
        }
        
    }

    public class MyAuthorizationRoot : AuthorizationRoot
    {
        private readonly IRequestFactory _requestFactory;
        private readonly OAuth2ConfigurationSection _configurationSection;

        public MyAuthorizationRoot() :
            this(new ConfigurationManager(), "oauth2", new RequestFactory())
        {
        }

        public MyAuthorizationRoot(
           IConfigurationManager configurationManager,
           string configurationSectionName,
           IRequestFactory requestFactory)
        {
            _requestFactory = requestFactory;
            _configurationSection = configurationManager
                .GetConfigSection<OAuth2ConfigurationSection>(configurationSectionName);
        }

        public override IEnumerable<IClient> Clients
        {
            get
            {
                var clients = base.Clients.ToList();
                var googleClient = clients.FirstOrDefault(x => x.Name == "Google");
                var newGoogleClient = new MyGoogleClient(_requestFactory, googleClient.Configuration);

                clients.Remove(googleClient);
                clients.Add(newGoogleClient);
                
                return clients;
            }
        }

        
    }
}
```

**Comment by niemyjski** [comment]
I don't see where you are storing the extra info? I think we should add a dictionary on the user info and stick it in there.  Would anyone like to take a stab at this?
