### ISSUE TITLE
How to return the user to the original url

### ISSUE THREAD

**Issue by ProNotion** [titarenko/OAuth2#63]
Because the redirect url is preconfigured how can we ensure the user user is redirected back to their original url? Is the only way to store something in session prior to the login?

Aside from this thanks so much for sharing as I've had a nightmare trying to get a working OAuth2 solution to fit into an existing app. I've written a Yahoo provider also now so will send a pull request when I'm finished.

Thanks, Simon

**Comment by niemyjski** [comment]
I only use this on my server side end point to validate a token/auth my api. We have a angular app that uses https://github.com/sahat/satellizer to request an auth code via our client side app. You can take a look at all of our code on how we handle this [here](https://github.com/exceptionless/Exceptionless.UI) and [here](https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Controllers/AuthController.cs).

What are you using for your client side tech?

**Comment by jordisan** [comment]
@ProNotion , what we are doing is encoding the original URL in the `state` parameter before the call, and then read it after the callback and redirect the browser to the original URL

**Comment by niemyjski** [comment]
What's the consensus on this issue?
