### ISSUE TITLE
Why can't I do this

### ISSUE THREAD

**Issue by mikkeljohnsen** [titarenko/OAuth2#65]
<pre>
			var cfg = new OAuth2.Configuration.RuntimeClientConfiguration {
				ClientId = "......",
				ClientSecret = "......"
			};
			var auth = new OAuth2.Client.OAuth2Client (cfg);

			return auth.GetToken ("https://api..../accesstoken");
</pre>

Please someone make a simple example, that don't involve config files and abstract class ?

**Comment by niemyjski** [comment]
Are you just trying to generically talk to an end point?

**Comment by mikkeljohnsen** [comment]
I enden up not using this.

**Comment by titarenko** [comment]
Hi, @mikkeljohnsen 

Nothing prevents you from doing something like
```csharp
var myClient = new GoogleClient(new RequestFactory(), new MyGoogleClientConfiguration());
// then do whatever you want with myClient
```
where `MyClientConfiguration` is implementation of corresponding interface which is NOT using config files, but is taking your credentials from other preferred place (for example, it can be simply hardcoded or whatever you want). 

P.S. Sorry for late response, and I hope you are satisfied with alternative solution.
