### ISSUE TITLE
Allow custom clients to be discovered

### ISSUE THREAD

**Issue by ProNotion** [titarenko/OAuth2#67]
Currently it is not possible to add your own custom clients from your own assembly. This means that unless it is an existing client native to this project you have to create a custom build of the project. I've forked the project and made a small change to allow discovery of clients in other assemblies and will initiate a pull request shortly for consideration.

Thanks, Simon

**Comment by ProNotion** [comment]
Pull request #68

**Comment by niemyjski** [comment]
Thanks for the pull request, I've added a comment on the issue.

**Comment by Avaq** [comment]
:+1: Would use.

**Comment by niemyjski** [comment]
@ProNotion could you take a look at my comment.. Also, is there any chance you could help me fix the unit tests so I can push a new build.

**Comment by ProNotion** [comment]
Sorry I missed this previously - will check and respond to your comment on the PR now.

**Comment by ProNotion** [comment]
Did I cause all of those tests to fail?

**Comment by niemyjski** [comment]
Nope, they were failing before I was here not sure what is causing them but some help would be greatly appreciated as I won't be able to look into them until I have a free weekend :(.

**Comment by ProNotion** [comment]
I will see what I can do for you.

**Comment by niemyjski** [comment]
I've merged this pull request. We just need to get the unit tests passing before we can release a new build to nuget.
