### ISSUE TITLE
Fix broken unit tests

### ISSUE THREAD

**Issue by niemyjski** [titarenko/OAuth2#70]

**Comment by niemyjski** [comment]
@ProNotion Can you help with this?

**Comment by ProNotion** [comment]
I started looking at it but didn't manage to get anywhere with it. I am away for the remainder of this week but if I get the chance I will see if I can look it while I'm away unless anyone else gets to it before me.

**Comment by ProNotion** [comment]
Pull request coming with all tests passing but I need a sanity check on this please as even though they are passing I am not 100% sure that the changes I have made are appropriate.

**Comment by niemyjski** [comment]
Thanks for the pull request. I made some comments on the code.

**Comment by niemyjski** [comment]
@ProNotion Thanks for taking the time to due a pull request. It put me in the right direction. I closed it because I've made some changes that I want to get reviewed. Can you please review my latest commit (and read the comment.

**Comment by niemyjski** [comment]
@titarenko, Can you email me info for the build server.. I'd like to be able to trigger a build etc..

**Comment by niemyjski** [comment]
@titarenko Can you trigger a clean build.. It looks like there is an issue with the build server.. My changes build locally via msbuild and vs.

**Comment by titarenko** [comment]
@niemyjski ok, I will try to do this at evening (in 5-10 hours, currently I have no access there).

**Comment by titarenko** [comment]
Manually triggered the build: it fails with error `Steps\CommonSteps.cs(4, 7): error CS0246: The type or namespace name 'FluentAssertions' could not be found (are you missing a using directive or an assembly reference?)`
