### ISSUE TITLE
Adding parameter to UserInfoServiceEndPoint

### ISSUE THREAD

**Issue by ProNotion** [titarenko/OAuth2#76]
I am trying to get a Yahoo client working and they make you jump through hoops to get at the profile. 

```
protected override Endpoint UserInfoServiceEndpoint
{
  get
  {
    return new Endpoint()
    {
      BaseUri = "https://social.yahooapis.com",
      Resource = "/v1/user/{guid}/profile/usercard"
    };
  }
}
```

The value I need for {guid} should be returned in the Request token response but how can I can get that value at this point? I think maybe I've been looking at this too long?

Thanks, Simon

**Comment by niemyjski** [comment]
I think you can get this by overriding ParseUserInfo method and parsing it out. Were you able to do this?

**Comment by niemyjski** [comment]
I think you can get this by overriding ParseUserInfo method and parsing it out. Were you able to do this?
