### ISSUE TITLE
how to get success status code after successful login

### ISSUE THREAD

**Issue by vinothrao** [titarenko/OAuth2#77]
how to get success status code after successful login? Is there any success code will be returned to the redirect uri. If anything how to get?

**Comment by niemyjski** [comment]
I'm not sure, you'd need to step through the code and take a look.

**Comment by hawk-i-** [comment]
in OAuth2.Client.OAuth2Client.cs there is a method QueryAccessToken method at line 192. in this method at line 205 a ExecuteAndVerify call is made to IRestClient object. if there is an error this method throws exception with response object. you can use this response object to get exact http error code and perform desired error handling and if it doesn't throw any exception then you can assume that the request was success

**Comment by hawk-i-** [comment]
i think the fact that it throws exception when somethinng goes off the rails should be enough

**Comment by titarenko** [comment]
@hawk-i- when your user did login, for example using her Google account, Google will redirect she back to your app (you are controlling where exactly user will be returned), in example app [it is Auth method of Home controller](https://github.com/titarenko/OAuth2/blob/master/OAuth2.Example/Controllers/HomeController.cs#L56-L59) everything that provider returns is in `Request.QueryString`, [as you can see here](https://github.com/titarenko/OAuth2/blob/master/OAuth2.Example/Controllers/HomeController.cs#L58)
