### ISSUE TITLE
Use Sample

### ISSUE THREAD

**Issue by PedroC88** [titarenko/OAuth2#78]
Is it possible to have a use sample? I'm new to the whole **web** development and I'm doing a personal project. I have already installed the package and modified the web.config, but I'm lost in how to implement it.

If I'm instructed on how to use it, I wouldn't mind creating some documentation for future references and posting it here.

**Comment by niemyjski** [comment]
Here is a real world use case where we use this library: https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Controllers/AuthController.cs

**Comment by LVG5Pelican** [comment]
Have any other resources available? The above resource has been removed

**Comment by niemyjski** [comment]
I've updated the link
