### ISSUE TITLE
Are there any plans for a Yahoo endpoint?

### ISSUE THREAD

**Issue by jaguire** [titarenko/OAuth2#79]
If not, mind if I play with creating one?

**Comment by ProNotion** [comment]
I have one that I'm using but it's not working as it should at present because it asks for approval everytime you login which I'm sure is not right. Happy to share if it will help reach a better end result.

**Comment by titarenko** [comment]
@jaredmcguire @ProNotion Sure, pull-requests are always welcome!

**Comment by ProNotion** [comment]
I was kind of hoping for feedback on it if I am honest as another pair of eyes will more likely spot what I've done wrong and why users are asked to approve for every login. I will try and get it up this afternoon. Should I still send a PR for feedback?

**Comment by niemyjski** [comment]
Yes! Having any support for yahoo is better than none.

**Comment by skasturi** [comment]
I added Yahoo client

**Comment by titarenko** [comment]
@skasturi added it in PR #89, I'm closing this issue - reopen if there are any problems
