### ISSUE TITLE
Dll version error on Clone > Build > Run VS15

### ISSUE THREAD

**Issue by davvit** [titarenko/OAuth2#83]
`"Could not load file or assembly 'Autofac, Version=**2.6.3.862**, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

=== Pre-bind state information ===
LOG: DisplayName = Autofac, Version=2.6.3.862, Culture=neutral, PublicKeyToken=17863af14b0044da
 (Fully-specified)
LOG: Appbase = file:///C:/Users/briod/Desktop/OAuthTest/OAuth2/Oauth2/OAuth2.Example/
LOG: Initial PrivatePath = C:\Users\briod\Desktop\OAuthTest\OAuth2\Oauth2\OAuth2.Example\bin
Calling assembly : Autofac.Integration.Mvc, Version=2.6.3.862, Culture=neutral, PublicKeyToken=17863af14b0044da.

LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\briod\Desktop\OAuthTest\OAuth2\Oauth2\OAuth2.Example\web.config
LOG: Using host configuration file: C:\Users\briod\Documents\IISExpress\config\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Autofac, Version=2.6.3.862, Culture=neutral, PublicKeyToken=17863af14b0044da
LOG: Attempting download of new URL file:///C:/Users/briod/AppData/Local/Temp/Temporary ASP.NET Files/vs/e002a6b1/3f91f652/Autofac.DLL.
**LOG: Attempting download of new URL file:///C:/Users/briod/AppData/Local/Temp/Temporary ASP.NET Files/vs/e002a6b1/3f91f652/Autofac/Autofac.DLL.**
LOG: Attempting download of new URL file:///C:/Users/briod/Desktop/OAuthTest/OAuth2/Oauth2/OAuth2.Example/bin/Autofac.DLL.
WRN: **Comparing the assembly name resulted in the mismatch: Major Version**
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.`

the new downloaded Autofac.DLL has newer version **3.5.2.**

**Comment by davvit** [comment]
In Package Manger terminal i did 
`PM> Install-Package Autofac -Version 2.6.3.862`

followed by Clean solution > rebuild > Debug OAuth2.Example

i get the following error

> Server Error in '/' Application.
> 
> Method not found: 'Autofac.Builder.IRegistrationBuilder`3<!0,!1,!2> Autofac.Builder.IRegistrationBuilder`3.InstancePerMatchingLifetimeScope(System.Object)'.
> 
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
> 
> Exception Details: System.MissingMethodException: Method not found: 'Autofac.Builder.IRegistrationBuilder`3<!0,!1,!2> Autofac.Builder.IRegistrationBuilder`3.InstancePerMatchingLifetimeScope(System.Object)'.
> 
> Source Error: 
> 
> 
> Line 69:             var builder = new ContainerBuilder();
> Line 70: 
> Line 71:             builder.RegisterModelBinders(Assembly.GetExecutingAssembly());
> Line 72:             builder.RegisterControllers(Assembly.GetExecutingAssembly());
> Line 73: 
> 
> Source File: C:\Users\briod\Desktop\OAuthTest\OAuth2\Oauth2\OAuth2.Example\Global.asax.cs    Line: 71

**Comment by niemyjski** [comment]
I think the dependencies need to be updated. Would you mind submitting a pr for this?

**Comment by niemyjski** [comment]
I'm going to be adding support for netstandard at some point.

**Comment by davvit** [comment]
Made a pull request. #84 
Learned a lot about git while doing this. Thanks for asking me to do this.

**Comment by titarenko** [comment]
Hi @davvit ! Thank you for contribution, your PR is merged and build is successful, probably, we can close this issue, can't we?

**Comment by davvit** [comment]
Yes we can close it.
