### ISSUE TITLE
facebook /oauth/access_token request does not return JSON

### ISSUE THREAD

**Issue by bennidhamma** [titarenko/OAuth2#86]
So I get a JSON parse error when I'm using OAuth2. Any idea what might be going on?

**Comment by niemyjski** [comment]
I'm not sure, have you tried seeing what scopes you are requesting?

**Comment by bennidhamma** [comment]
yea. i hacked in '2.7' into the resource url to force the newer version and
that seemed to work.

**Comment by niemyjski** [comment]
@bennidhamma can you create a pr for this, it would be greatly appreciated.

**Comment by plixxer** [comment]
This post seems to be abandoned can we close this.
