### ISSUE TITLE
https://github.com/niemyjski

### ISSUE THREAD

**Issue by amanh47** [titarenko/OAuth2#88]
Hi Dear,
i have create NetTier solution with webservice and webprojectApp now i can access data from my database using sqlClient but when i use Webservice to get my data i faced the following Problem....
can you please help me. 

Exception Text : "An exception of type 'System.Net.WebException' occurred in CORN.Data.WebServiceClient.dll but was not handled in user code.
Additional information: The operation has timed out"

I worked  as :
1. Set Default Provider "WsNetTiersProvider" in both (Webservice & Website)  Web.Config files.
2. Write code as
TList<CHECK_BOOK> tList = DataRepository.CHECK_BOOKProvider.GetAll();
            GridView.DataSource = tList;
            GridView.DataBind();

Aman Ullah

**Comment by titarenko** [comment]
Hi @amanh47 

Is this issue related to OAuth library?

**Comment by niemyjski** [comment]
This is not related to this project.
