### ISSUE TITLE
Acceptance Tests

### ISSUE THREAD

**Issue by titarenko** [titarenko/OAuth2#9]
Create acceptance tests using browser automation to ensure each and every client is fully working.

**Comment by skasturi** [comment]
@titarenko Are you working on this now? I am wondering when we would be able to push a release version of this library.

**Comment by titarenko** [comment]
No, currently I do not work on this (unfortunately, I do not have spare time to proceed with this task). Regarding release version: 0.8 de-facto is a release version (formally, I wanted to finalize acceptance tests before changing version to 1.0).
