### ISSUE TITLE
IEnumerable for IClient

### ISSUE THREAD

**Issue by elfico** [titarenko/OAuth2#91]
Hello. I installed the Package via nugets and followed the example you have in the readme. But the code is throwing error since IClient is a type of IEnumerable but you example says to use it as 

var uri = authorizationRoot.Clients[0].GetLoginLinkUri();

How can this be overcome?

**Comment by titarenko** [comment]
authorizationRoot.First().GetLoginLinkUri();

**Comment by elfico** [comment]
Thanks. I was able to cast it to a list and use it. 
The access token that is return is shown in my URL. Can this be hidden?
Sorry if I am asking too many questions, I am new to Oauth2.

**Comment by elfico** [comment]
Hi @titarenko , please I am having an issue with the plugin. I integrated it and it worked well, but sometimes, when I tried to get the authorization, it shows error 404. Please what can iI do about it?

**Comment by skasturi** [comment]
404 usually means your routes are not setup correctly. When you run OAuth2 Test project you should see a page with the list of providers specified in the Web.Config.

**Comment by niemyjski** [comment]
@elfico if you are still seeing this issue, would you mind opening a new issue.
