### ISSUE TITLE
Load configuration from database

### ISSUE THREAD

**Issue by tgiachi** [titarenko/OAuth2#93]
Hi!,
Is possibile create configuration at runtime? For example: read configuration from database and create Configuration?

Thanks you

**Comment by titarenko** [comment]
Hi!

Sure, you can create authorization root using [this constructor](https://github.com/titarenko/OAuth2/blob/master/OAuth2/AuthorizationRoot.cs#L36) providing it with custom implementation of `IConfigurationManager`, or you can use client implementations directly, creating instances using [for example, this constructor](https://github.com/titarenko/OAuth2/blob/master/OAuth2/Client/Impl/InstagramClient.cs#L21).

**Comment by niemyjski** [comment]
Please let us know if you have any more questions
