### ISSUE TITLE
Support for ASP.NET Core

### ISSUE THREAD

**Issue by tynar** [titarenko/OAuth2#98]
Support for ASP.NET Core

**Comment by niemyjski** [comment]
We'd be willing to accept a pr for this

**Comment by niemyjski** [comment]
I just merged in support for .net standard 2.0. Can you please check the build server for artifacts and let us know if you have any questions or issues.

**Comment by niemyjski** [comment]
@titarenko  We just pushed an updated build with official restsharp support.
